export const breadcrumbMap: Record<string, { label: string; parent?: string }> =
  {
    '/': { label: 'tungsten' },
    '/root': { label: '', parent: '/' },
    '/login': { label: 'login', parent: '/' },
    '/system-health': { label: 'system-health', parent: '/' },
    '/users': { label: 'users', parent: '/' },
    '/users/:id': { label: '...', parent: '/users' },
    '/notes': { label: 'notes', parent: '/' },
    '/notes/:id': { label: '...', parent: '/notes' },
    '/media': { label: 'media', parent: '/' },
    '/media/:bucketId': { label: '...', parent: '/media' },
    '/media/:bucketId/files/:id': {
      label: '...',
      parent: '/media/:bucketId',
    },
    '/templates': { label: 'templates', parent: '/' },
    '/templates/:id': { label: '...', parent: '/templates' },
    '/sandbox': { label: 'sandbox', parent: '/' },
    '/sandbox/:id': { label: '...', parent: '/sandbox' },
    '/chat': { label: 'chat', parent: '/' },
    '/chat/:id': { label: '...', parent: '/chat' },
    '/chat-bot': { label: 'chat-bot', parent: '/' },
    '/chat-bot/:id': { label: '...', parent: '/chat-bot' },
    '/image-generation': { label: 'image-generation', parent: '/' },
    '/image-generation/:id': { label: '...', parent: '/image-generation' },
    '/background-jobs': { label: 'background-jobs', parent: '/' },
    '/background-jobs/:id': { label: '...', parent: '/background-jobs' },
    '/queues': { label: 'queues', parent: '/' },
    '/queues/:id': { label: '...', parent: '/queues' },
    '/inbox': { label: 'inbox', parent: '/' },
    '/topics': { label: 'topics', parent: '/' },
    '/topics/discover': { label: 'discover', parent: '/topics' },
    '/topics/system': { label: 'system', parent: '/topics' },
    '/topics/:id': { label: '...', parent: '/topics' },
    '/recipients': { label: 'recipients', parent: '/' },
    '/notifications': { label: 'notifications', parent: '/' },
    '/notifications/admin': { label: 'admin', parent: '/notifications' },
    '/quotas': { label: 'quotas', parent: '/' },
    '/events/failed': { label: 'failed-events', parent: '/' },
    '/config': { label: 'config', parent: '/' },
    '/help': { label: 'help', parent: '/' },
    '/profile': { label: 'profile', parent: '/' },
  };
